In [1]:
import pandas as pd

In [2]:
with open('./data/yahoo_movie_dataset/ydata-ymovies-mapping-to-movielens-v1_0.txt', 'r', encoding='ISO-8859-1') as file:
    ym_m = file.read()
ym_m = ym_m.split("\n")

In [3]:
with open('./data/yahoo_movie_dataset/ydata-ymovies-movie-content-descr-v1_0.txt', 'r', encoding='ISO-8859-1') as file:
    ym_meta = file.read()
ym_meta = ym_meta.split("\n")

In [4]:
ym_meta = ["\t".join(info.split("\t")[:18]) for info in ym_meta]
# ym_meta = ["\t".join(info.split("\t")) for info in ym_meta]

In [5]:
for data in ym_meta:
    try:
        if 'Toy Story (1995)' in data.split("\t")[1]:
            for a in data.split("\t"):
                print(a)
    except:
        break

1800247298
Toy Story (1995)
Woody, a traditional pull-string talking cowboy, has long enjoyed a place of honor as the favorite among six-year-old Andy's menagerie of toys. Quick to calm their anxieties about being replaced by newer arrivals, Woody finds his own confidence shaken, and his status as top toy in jeopardy, upon the arrival of Buzz Lightyear, simply the coolest space action figure ever made. Woody plots to get rid of Buzz, but things backfire and he finds himself lost in the outside world with Buzz as his only companion. Joining forces to find their way home, the two rivals set out on an adventure that lands them in the clutches of Sid, a sadistic neighborhood kid who is notorious for dismembering and reassembling mutant toys in his bedroom. As guests of Sid and his dog, Scud, the two fugitive toys forge a genuine friendship and learn that only through mutual trust and respect do they have any chance of survival.
1 hr. 17 min.
G
\N
November 22, 1995 Nationwide
19951122
Buena Vista Distribution Compa
allposters/98/1800247298p-th.jpg
Comedy|Kids/Family
John Lasseter
1800019798
Screenwriter|Voice|Executive Producer|Screenwriter|Executive Producer|Voice|Voice|Producer|Screenwriter, Story|Voice|Music|Producer|Screenwriter, Story|Voice|Voice|Voice|Screenwriter|Voice|Voice|Screenwriter|Screenwriter, Story|Screenwriter, Story|Voice|Screenwriter
Joel Cohen|Don Rickles|Steve Jobs|Joss Whedon|Edwin Catmull| Teller|Laurie Metcalf|Ralph Guggenheim|Andrew Stanton|Annie Potts|Randy Newman|Bonnie Arnold|Pete Docter|John Ratzenberger|Jim Varney|Wallace Shawn|Alec Sokolow|Tim Allen|Tom Hanks|Peter Docter|Joe Ranft|John Lasseter|R. Lee Ermey| Alec
1800022110|1800021296|1800373104|1800175424|1800373102|1800373095|1800020946|1800373100|1800019799|1800032974|1800049227|1800025024|1807614748|1800036961|1800021600|1800022784|1800238568|1800021848|1800010392|1807615112|1800019803|1800019798|1800040602|1804032664
Tom Hanks|Tim Allen|Don Rickles|Annie Potts|John Ratzenberger
1800010392|1800021848|1800021296|1800032974|1800036961

In [6]:
with open('./data/yahoo_movie_dataset/ydata-ymovies-user-demographics-v1_0.txt', 'r', encoding='ISO-8859-1') as file:
    ym_u = file.read()
ym_u = ym_u.split("\n")

In [7]:
with open('./data/yahoo_movie_dataset/ydata-ymovies-user-movie-ratings-test-v1_0.txt', 'r', encoding='ISO-8859-1') as file:
    ym_test = file.read()
ym_test = ym_test.split("\n")

In [8]:
with open('./data/yahoo_movie_dataset/ydata-ymovies-user-movie-ratings-train-v1_0.txt', 'r', encoding='ISO-8859-1') as file:
    ym_train = file.read()
ym_train = ym_train.split("\n")

In [9]:
ym_r = ym_test + ym_train

In [10]:
ym_m_dict = {"yahoo_movieId":list(), "title":list(), "movielens_movieId":list()}
ym_r_dict = {"userId":list(), "yahoo_movieId":list(), "yahoo_style_rating":list(), "rating":list()}
ym_u_dict = {"userId":list(), "birth_year":list(), "gender":list()}
ym_meta_dict = {"yahoo_movieId":list(), "title":list(), "synopsis":list(), "running_time":list(), "MPAA_rating":list(), "reason_MPAA_rating":list(), "release_date":list(), "release_date1":list(), "distributor":list(), "poster_url":list(), "genres":list(), "directors":list(), "director_ids":list(), "crew":list(), "crew_ids":list(), "crew_types":list(), "actors":list(), "actor_ids":list()}

In [11]:
ym_m[0].split("\t")

['1800247298', 'Toy Story (1995)', '1']

In [12]:
for val in ym_m:
    try:
        ymid, t, mid = val.split("\t")
        ym_m_dict["yahoo_movieId"].append(ymid)
        ym_m_dict["title"].append(t)
        ym_m_dict["movielens_movieId"].append(mid)
    except:
        print(val)

In [13]:
ym_r[0].split("\t")

['5', '1808405757', '9', '4']

In [14]:
for val in ym_r:
    try:
        uid, ymid, yr, r = val.split("\t")
        ym_r_dict["userId"].append(uid)
        ym_r_dict["yahoo_movieId"].append(ymid)
        ym_r_dict["yahoo_style_rating"].append(yr)
        ym_r_dict["rating"].append(r)
    except:
        print(val)

In [15]:
for val in ym_u:
    try:
        uid, by, gen = val.split("\t")
        ym_u_dict["userId"].append(uid)
        ym_u_dict["birth_year"].append(by)
        ym_u_dict["gender"].append(gen)
    except:
        print(val)

In [16]:
for val in ym_meta:
    try:
        
        ymid, t, s, rt, Mr, rMr, rd, rd1, dis, poster, g, d, did, c, cid, ct, a, aid = val.split("\t")
        ym_meta_dict["yahoo_movieId"].append(ymid)
        ym_meta_dict["title"].append(t)
        ym_meta_dict["synopsis"].append(s)
        ym_meta_dict["running_time"].append(rt)
        ym_meta_dict["MPAA_rating"].append(Mr)
        ym_meta_dict["reason_MPAA_rating"].append(rMr)
        ym_meta_dict["release_date"].append(rd)
        ym_meta_dict["release_date1"].append(rd1)
        ym_meta_dict["distributor"].append(dis)
        ym_meta_dict["poster_url"].append(poster)
        ym_meta_dict["genres"].append(g)
        ym_meta_dict["directors"].append(d)
        ym_meta_dict["director_ids"].append(did)
        ym_meta_dict["crew"].append(c)
        ym_meta_dict["crew_ids"].append(cid)
        ym_meta_dict["crew_types"].append(ct)
        ym_meta_dict["actors"].append(a)
        ym_meta_dict["actor_ids"].append(aid)
    except:
        print(val)

In [17]:
ym_meta_df = pd.DataFrame(ym_meta_dict)
ym_u_df = pd.DataFrame(ym_u_dict)
ym_r_df = pd.DataFrame(ym_r_dict)
ym_m_df = pd.DataFrame(ym_m_dict)

In [20]:
# Data decontamination on ym_m_df
# Contamination: some does not contain yahoo_movieId or some has different title while 'yahoo_movieId' is same.
ym_m_df[ym_m_df.yahoo_movieId.duplicated()]

     yahoo_movieId                              title movielens_movieId
31                              Twelve Monkeys (1995)                32
58                           Confessionnal, Le (1995)                59
72                             Misérables, Les (1995)                73
75      1800249953                   Screamers (1995)                76
79                             Badkonake Sefid (1995)                80
...            ...                                ...               ...
3815    1808428930                  Love & Sex (2000)              3885
3820    1800359660                  Back Stage (2000)              3890
3865                                    Kronos (1973)              3935
3870                Slumber Party Massacre III (1990)              3940
3872                Sorority House Massacre II (1990)              3942

[352 rows x 3 columns]

In [21]:
contaminated_yahoo_movieId = list(ym_m_df[ym_m_df.yahoo_movieId.duplicated()].yahoo_movieId.unique())
ym_m_df = ym_m_df[~ym_m_df.yahoo_movieId.duplicated()]

In [22]:
# also drop contaminated_yahoo_movieId on ym_meta_df and ym_r_df
ym_r_df = ym_r_df[~ym_r_df.yahoo_movieId.isin(contaminated_yahoo_movieId)]
ym_meta_df = ym_meta_df[~ym_meta_df.yahoo_movieId.isin(contaminated_yahoo_movieId)]

In [23]:
ym_meta_df

,yahoo_movieId,title,synopsis,running_time,MPAA_rating,reason_MPAA_rating,release_date,release_date1,distributor,poster_url,genres,directors,director_ids,crew,crew_ids,crew_types,actors,actor_ids
0,1800010969,The 1985 Admiral's Cup (1997),Small boats vs. big winds in this the official...,\N,\N,\N,,\N,\N,\N,Special Interest,\N,\N,\N,\N,\N,\N,\N
1,1800011786,984 - Prisoner of the Future (1984),"984, a man of the future, is imprisoned withou...",\N,\N,\N,,\N,\N,\N,Science Fiction/Fantasy,\N,\N,\N,\N,\N,\N,\N
2,1800011850,A's All-Star Almanac (1987),Seen here are great moments from All-Star Game...,\N,\N,\N,,\N,\N,\N,Special Interest,\N,\N,\N,\N,\N,\N,\N
3,1800012991,The Adventures of Annie Oakley (1953),"Two great episodes of this western series. ""An...",\N,\N,\N,,\N,\N,\N,Western,\N,\N,Featured,Jimmy Hawkins,1800012997,Gail Davis|Brad Johnson (II),1800012993|1804514319
4,1800013061,The Adventures of Black Beauty 1 (1972),"""The Fugitive"" introduces the story of the onc...",\N,\N,\N,,\N,\N,\N,Kids/Family,\N,\N,\N,\N,\N,Judi Bowker,1800013063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106954,1808524892,The Saragossa Manuscript (1999),Based on the early 19th century novel by Polis...,2 hrs. 30 min.,NR,\N,"May 21, 1999 Limited",19990521,Cowboy Booking International,\N,Art/Foreign|Comedy,Wojciech Has,1800024356,Screenwriter|Producer,Tadeusz Kwiatkowski|Kamerafilm Unit,1800024357|1800026072,Iga Cembrzynska-Kondratiuk|Zbigniew Cybulski|J...,1800024354|1800019663|1800019662|1800024355
106955,1808524895,For Ever Mozart (1997),A meditation on the war in Bosnia and the proc...,1 hr. 24 min.,NR,\N,"July 4, 1997",19970704,\N,\N,\N,Jean-Luc Godard,1800016212,\N,\N,\N,\N,\N
106956,1808524896,Northern Skirts (1999),Party-girl and native Austrian Jasmin is a bus...,1 hr. 43 min.,NR,\N,"January 1, 1999",19990101,\N,\N,\N,Barbara Albert,1807473704,\N,\N,\N,\N,\N
106957,1808524899,Valley of Tears (2003),An examination of the lives of Mexican-America...,1 hr. 22 min.,NR,\N,"November 19, 2003 NY",20031119,7th Art,\N,Documentary,Hart Perry,1800074729,Screenwriter|Producer,Juan Gonzales|Hart Perry,1808524900|1800074729,\N,\N
106958,1808525209,Morlang (2003),"Based on a true story, a psychological drama a...",1 hr. 34 min.,NR,\N,"December 12, 2003 Limited",20031212,Flim Movement,\N,Drama,Tjebbo Penning,1808414989,Screenwriter|Screenwriter|Producer,Tjebbo Penning|Matthew Faulk|Petra Goedings,1808414989|1808525211|1808525210,Paul Freeman|Susan Lynch|Diana Kent|Eric van d...,1800022152|1800019877|1800226260|1808414990|18...

In [24]:
ym_meta_df.columns

Index(['yahoo_movieId', 'title', 'synopsis', 'running_time', 'MPAA_rating',
       'reason_MPAA_rating', 'release_date', 'release_date1', 'distributor',
       'poster_url', 'genres', 'directors', 'director_ids', 'crew', 'crew_ids',
       'crew_types', 'actors', 'actor_ids'],
      dtype='object')

In [25]:
ym_meta_df.drop(labels=["synopsis", "running_time", "MPAA_rating", "release_date", "release_date1", "reason_MPAA_rating", "poster_url", 'director_ids', 'crew_ids', 'actor_ids'], inplace=True, axis=1)

In [26]:
ym_meta_df.to_csv("./data/yahoo_movie_dataset/movies_meta.csv", index=False)
ym_u_df.to_csv("./data/yahoo_movie_dataset/users.csv", index=False)
ym_r_df.to_csv("./data/yahoo_movie_dataset/ratings.csv", index=False)
ym_m_df.to_csv("./data/yahoo_movie_dataset/movies.csv", index=False)

In [27]:
ym_m_df

     yahoo_movieId                               title movielens_movieId
0       1800247298                    Toy Story (1995)                 1
1       1800022746                      Jumanji (1995)                 2
2       1800250021             Grumpier Old Men (1995)                 3
3       1800249828            Waiting to Exhale (1995)                 4
4       1800249488  Father of the Bride Part II (1995)                 5
...            ...                                 ...               ...
3878    1802761123             Meet the Parents (2000)              3948
3879    1800361191          Requiem for a Dream (2000)              3949
3880    1802956884                    Tigerland (2000)              3950
3881    1800354250             Two Family House (2000)              3951
3882    1800421220               Contender, The (2000)              3952

[3531 rows x 3 columns]

In [37]:
tmp = pd.merge(ym_m_df, ym_meta_df, on="yahoo_movieId", how="inner").drop(labels=["title_y"], axis=1)

In [40]:
df = tmp.rename(columns={"title_x":"title"})

In [42]:
for col in df.columns:
    df[col] = df[col].apply(lambda x:x if x != "\\N" else "")

In [43]:
df

,yahoo_movieId,title,movielens_movieId,distributor,genres,directors,crew,crew_types,actors
0,1800247298,Toy Story (1995),1,Buena Vista Distribution Compa,Comedy|Kids/Family,John Lasseter,Screenwriter|Voice|Executive Producer|Screenwr...,1800022110|1800021296|1800373104|1800175424|18...,Tom Hanks|Tim Allen|Don Rickles|Annie Potts|Jo...
1,1800022746,Jumanji (1995),2,,Kids/Family,Joe Johnston,Composer,1800011556,Robin Williams|Bonnie Hunt|Kirsten Dunst|Bradl...
2,1800250021,Grumpier Old Men (1995),3,,Comedy,Howard Deutch,Editor,1800054420,Walter Matthau|Jack Lemmon| Ann-Margret|Sophia...
3,1800249828,Waiting to Exhale (1995),4,,Drama,Forest Whitaker,,,Whitney Houston|Angela Bassett|Lela Rochon|Lor...
4,1800249488,Father of the Bride Part II (1995),5,,Comedy,Charles Shyer,Screenwriter,1800025966,Steve Martin|Diane Keaton|Martin Short|Kimberl...
...,...,...,...,...,...,...,...,...,...
3415,1802761123,Meet the Parents (2000),3948,Universal Pictures,Comedy,Jay Roach,Screenwriter|Producer|Producer|Producer|Screen...,1800315268|1800280627|1800018680|1800179486|18...,Robert De Niro [Jack Byrnes]|Ben Stiller [Greg...
3416,1800361191,Requiem for a Dream (2000),3949,Artisan Entertainment,Drama,Darren Aronofsky,Composer|Screenwriter|Editor|Composer|Cinemato...,1800398046|1800023984|1800242278|1800319878|18...,Ellen Burstyn [Sara]|Jared Leto [Harry]|Jennif...
3417,1802956884,Tigerland (2000),3950,Twentieth Century Fox,Drama,Joel Schumacher,Editor|Screenwriter|Producer|Screenwriter|Prod...,1800052369|1802956888|1800022663|1800298163|18...,Colin Farrell [Bozz]|Clifton Collins|Tom Guiry...
3418,1800354250,Two Family House (2000),3951,Lions Gate Films,Drama,Raymond DeFelitta,Executive Producer|Producer|Screenwriter|Produ...,1800327293|1800354365|1800292658|1803470619|18...,Michael Rispoli|Kelly MacDonald [Mary O'Neary]...
3419,1800421220,"Contender, The (2000)",3952,Dreamworks SKG,Drama,Rod Lurie,Costume Designer|Screenwriter|Production Desig...,1804019409|1800353450|1804019408|1800349188|18...,Joan Allen [Senator Laine Hanson]|Christian Sl...

In [61]:
def f1(x:str):
    if "/I" in x:
        return x.replace("/I", "")
    else:
        return x

def f2(x:str):
    try:
        return str(int(f1(x).split()[-1].strip("\(").strip("\)")) // 10 * 10) + "'s"
    except:
        return ""

In [62]:
df["release_year"] = df["title"].apply(lambda x:f2(f1(x)))

In [70]:
df.sort_values(by=["movielens_movieId"], ascending=(True), inplace=True)

In [183]:
movielens_tmdb_df = pd.read_csv("./data/movielens_tmdb.csv")

In [184]:
movielens_tmdb_df

,movieId,title,release_year,origin_country,Writer,Original Story,Original Film Writer,Director,cast
0,1,Toy Story,1995.0,US,NaN,Pete Docter,NaN,John Lasseter,Tom Hanks
1,1,Toy Story,1995.0,US,NaN,Pete Docter,NaN,John Lasseter,Annie Potts
2,2,Jumanji,1995.0,US,NaN,NaN,NaN,Joe Johnston,Robin Williams
3,2,Jumanji,1995.0,US,NaN,NaN,NaN,Joe Johnston,Kirsten Dunst
4,3,Grumpier Old Men,1995.0,NaN,Mark Steven Johnson,NaN,NaN,Howard Deutch,Daryl Hannah
...,...,...,...,...,...,...,...,...,...
52472,129826,The Pirates,2014.0,KR,Choi Lee-Young,NaN,NaN,Lee Suk-hoon,Lee Yi-kyung
52473,129830,The Rose of the Rascal,2001.0,FI,Vexi Salmi,NaN,NaN,Timo Koivusalo,Ilkka Koivula
52474,129830,The Rose of the Rascal,2001.0,FI,Vexi Salmi,NaN,NaN,Timo Koivusalo,Pertti Koivula
52475,129834,Innocence,2013.0,US,NaN,NaN,NaN,Hilary Brougher,Kelly Reilly
52476,129834,Innocence,2013.0,US,NaN,NaN,NaN,Hilary Brougher,Linus Roache

In [185]:
cast_list = movielens_tmdb_df.cast.to_list()
director_list = movielens_tmdb_df.Director.to_list()
writer_list = movielens_tmdb_df.Writer.to_list()
movieId_list = movielens_tmdb_df.movieId.to_list()

In [186]:
from collections import defaultdict
mw, md, mc = defaultdict(list), defaultdict(list), defaultdict(list)

In [187]:
for m, w, d, c in zip(movieId_list, writer_list, director_list, cast_list):
    mw[m].append(w)
    md[m].append(d)
    mc[m].append(c)

In [188]:
import numpy as np
np.NaN

nan

In [189]:
def f3(x, dic):
    a = dic[x]
    if np.NaN in a:
        return ""
    else:
        return a

In [190]:
movielens_tmdb_df.sample(1)

,movieId,title,release_year,origin_country,Writer,Original Story,Original Film Writer,Director,cast
45220,110297,Viola,2012.0,NaN,NaN,NaN,NaN,Matías Piñeiro,Alberto Ajaka

In [191]:
movielens_tmdb_df["writer"] = movielens_tmdb_df["movieId"].apply(lambda x:f3(x, mw))
movielens_tmdb_df.drop(labels=["Writer"], inplace=True, axis=1)

In [192]:
movielens_tmdb_df["director"] = movielens_tmdb_df["movieId"].apply(lambda x:f3(x, md))
movielens_tmdb_df.drop(labels=["Director"], inplace=True, axis=1)

In [193]:
movielens_tmdb_df["cast_"] = movielens_tmdb_df["movieId"].apply(lambda x:f3(x, mc))
movielens_tmdb_df.drop(labels=["cast"], inplace=True, axis=1)

In [194]:
movielens_tmdb_df.drop(labels=["Original Story", "Original Film Writer"], inplace=True, axis=1)

In [195]:
movielens_tmdb_df.rename(columns={"cast_":"cast"}, inplace=True)

In [196]:
movielens_tmdb_df

,movieId,title,release_year,origin_country,writer,director,cast
0,1,Toy Story,1995.0,US,,"[John Lasseter, John Lasseter]","[Tom Hanks, Annie Potts]"
1,1,Toy Story,1995.0,US,,"[John Lasseter, John Lasseter]","[Tom Hanks, Annie Potts]"
2,2,Jumanji,1995.0,US,,"[Joe Johnston, Joe Johnston]","[Robin Williams, Kirsten Dunst]"
3,2,Jumanji,1995.0,US,,"[Joe Johnston, Joe Johnston]","[Robin Williams, Kirsten Dunst]"
4,3,Grumpier Old Men,1995.0,NaN,"[Mark Steven Johnson, Mark Steven Johnson]","[Howard Deutch, Howard Deutch]","[Daryl Hannah, Sophia Loren]"
...,...,...,...,...,...,...,...
52472,129826,The Pirates,2014.0,KR,"[Choi Lee-Young, Choi Lee-Young]","[Lee Suk-hoon, Lee Suk-hoon]","[Son Ye-jin, Lee Yi-kyung]"
52473,129830,The Rose of the Rascal,2001.0,FI,"[Vexi Salmi, Vexi Salmi]","[Timo Koivusalo, Timo Koivusalo]","[Ilkka Koivula, Pertti Koivula]"
52474,129830,The Rose of the Rascal,2001.0,FI,"[Vexi Salmi, Vexi Salmi]","[Timo Koivusalo, Timo Koivusalo]","[Ilkka Koivula, Pertti Koivula]"
52475,129834,Innocence,2013.0,US,,"[Hilary Brougher, Hilary Brougher]","[Kelly Reilly, Linus Roache]"
52476,129834,Innocence,2013.0,US,,"[Hilary Brougher, Hilary Brougher]","[Kelly Reilly, Linus Roache]"

In [197]:
def f4(x):
    if isinstance(x, str):
        return ""
    else:
        x = list(set(x))
        return x[0]

movielens_tmdb_df["writer"] = movielens_tmdb_df["writer"].apply(lambda x:f4(x))
movielens_tmdb_df["director"] = movielens_tmdb_df["director"].apply(lambda x:f4(x))
movielens_tmdb_df["cast"] = movielens_tmdb_df["cast"].apply(lambda x:f4(x))

In [198]:
movielens_tmdb_df_ = movielens_tmdb_df.drop_duplicates()

In [199]:
movielens_tmdb_df_

,movieId,title,release_year,origin_country,writer,director,cast
0,1,Toy Story,1995.0,US,,John Lasseter,Tom Hanks
2,2,Jumanji,1995.0,US,,Joe Johnston,Robin Williams
4,3,Grumpier Old Men,1995.0,NaN,Mark Steven Johnson,Howard Deutch,Daryl Hannah
6,4,Waiting to Exhale,1995.0,US,,Forest Whitaker,Giancarlo Esposito
8,5,Father of the Bride Part II,1995.0,US,,Charles Shyer,Martin Short
...,...,...,...,...,...,...,...
52467,129820,Military Academy,2007.0,NaN,,Granz Henman,Axel Stein
52469,129822,"Feuer, Eis & Dosenbier",2002.0,NaN,,Mathias Dinter,Axel Stein
52471,129826,The Pirates,2014.0,KR,Choi Lee-Young,Lee Suk-hoon,Son Ye-jin
52473,129830,The Rose of the Rascal,2001.0,FI,Vexi Salmi,Timo Koivusalo,Ilkka Koivula
52475,129834,Innocence,2013.0,US,,Hilary Brougher,Kelly Reilly

In [200]:
movielens_tmdb_df_.to_csv("./data/ml_tmdb.csv", index=)